steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crm-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crm-backend:latest'
      - './backend'
    id: 'build-backend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=${_BACKEND_URL}'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=$PROJECT_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=${_FIREBASE_APP_ID}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crm-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crm-frontend:latest'
      - './frontend'
    id: 'build-frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crm-backend:$COMMIT_SHA']
    id: 'push-backend'
    waitFor: ['build-backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crm-frontend:$COMMIT_SHA']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crm-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crm-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,GCP_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets'
      - 'JWT_SECRET=JWT_SECRET:latest,DB_PASSWORD=DB_PASSWORD:latest'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crm-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crm-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

timeout: 1800s
options:
  machineType: 'N1_HIGHCPU_8'
